#!/usr/bin/bash
#
#  Copyright 2016 Matteo Alessio Carrara <sw.matteoac@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#


# TODO Esportare lista dei file al posto dei file (es. per i film)
# TODO Dichiarare alcuni file come costanti e avvisare se sono stati modificati (corruzione)
# TODO Controlli integrità periodici
# TODO Implementare hooks pre e post backup? (es. pre-download di dati online, post-compressione dei dati)


set -e -u


if [[ $# -lt 2 ]]
then
	echo "Uso: packup backup_root files"
	exit 1
fi


BKUP_ROOT="$1"
FILES=${@:2}
DEST="$BKUP_ROOT/$(date --iso-8601=seconds)"
PREV_BKUP="$(ls $BKUP_ROOT | sort | tail -n 1)"
[[ -n $PREV_BKUP ]] && OPT_CMD="--link-dest=$BKUP_ROOT/$PREV_BKUP" || OPT_CMD=""
[[ -n $PREV_BKUP ]] && echo Individuato backup precedente \($PREV_BKUP\)


mkdir $DEST
rsync --archive --recursive --relative --perms --human-readable --verbose $OPT_CMD $FILES $DEST