#!/usr/bin/bash
#
#  Copyright 2016 Matteo Alessio Carrara <sw.matteoac@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#


# TODO Dichiarare alcuni file come costanti e avvisare se sono stati modificati (corruzione)
# TODO Controlli integrità periodici


set -e -u


if [[ $# -lt 2 ]]
then
	echo "Uso: packup backup_root files"
	exit 1
fi


PRE_HOOKS_DIR=~/packup/pre
POST_HOOKS_DIR=~/packup/post
BKUP_ROOT="$1"
FILES=${@:2}
DEST="$BKUP_ROOT/$(date --iso-8601=seconds)"
PREV_BKUP="$(ls $BKUP_ROOT | sort | tail -n 1)"
[[ -n $PREV_BKUP ]] && OPT_CMD="--link-dest=$BKUP_ROOT/$PREV_BKUP" || OPT_CMD=""
[[ -n $PREV_BKUP ]] && echo Individuato backup precedente \($PREV_BKUP\)


if [[ -d $PRE_HOOKS_DIR ]]
then
	echo "Esecuzione degli script di pre-backup"
	for f in $(ls $PRE_HOOKS_DIR)
	do
		. $PRE_HOOKS_DIR/$f
	done
fi


mkdir $DEST
rsync --archive --relative --hard-links --human-readable --verbose $OPT_CMD $FILES $DEST


if [[ -d $POST_HOOKS_DIR ]]
then
	echo "Esecuzione degli script di post-backup"
	for f in $(ls $POST_HOOKS_DIR)
	do 
		. $POST_HOOKS_DIR/$f
	done
fi
